name: cypress-tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress E2E tests
        run: npm run test:e2e

      - name: Show Cypress results
        run: |
          echo "=== Cypress Test Results ==="
          ls -lah cypress/videos || echo "No Cypress videos found"
          ls -lah cypress/screenshots || echo "No screenshots found"